# Makefile for mylib
# make clean -f Makefile.pdlibbuilder && make -f Makefile.pdlibbuilder

lib.name = chips~

class.sources = atari2600~.c atari5200~.c colecovision~.c

datafiles = atari2600~-help.pd atari5200~-help.pd colecovision~-help.pd

PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder